service: smashcentral

provider:
  name: aws
  runtime: nodejs6.10

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: matches
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: matches/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
      - http:
         path: matches
         method: get
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: matches/{id}
         method: delete
         cors: true


  